plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

theme: jekyll-theme-cayman

links:
  - name: 所有
    url: /
    type: recent
    external: false

  - name: 随笔
    url: /
    type: recent
    external: false

  - name: 技术篇
    url: /
    type: recent
    external: false


# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts"
#     values:
#       layout: "post"

repositories:
  limit: 9
  sort_by_stars: true

article:
  - name: 技术博客
    web_url: https://shilong.js.org
    image_url: https://user-images.githubusercontent.com/26021085/164876954-f53ae257-472b-4eb4-b4f2-b244597e77b5.png

topics:
  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://user-images.githubusercontent.com/26021085/164583257-119c3fb6-778d-4aeb-9d76-46bb2932dccc.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://user-images.githubusercontent.com/26021085/164872756-6dd4fff7-8ead-43d1-8bd5-d9e334aa0f1d.png

  - name: JavaScript
    web_url: https://github.com/topics/js
    image_url: https://user-images.githubusercontent.com/26021085/164877093-90ed0fce-9ee4-4ce2-be91-0cd7eba48d07.png

  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://user-images.githubusercontent.com/26021085/164872865-ec6a8ca4-0da8-4945-b67a-7f3b244106a5.png

  - name: VS_Code
    web_url: https://github.com/topics/vscode
    image_url: https://user-images.githubusercontent.com/26021085/164877246-fbdfccc2-da7b-4c28-9c77-3f38764dfa0c.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://user-images.githubusercontent.com/26021085/164877362-16a3593d-1f08-449e-b582-5c36671eab91.png
